package Transaction;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import Account.Account;
import BankingApp.Mainclass;
import generic.Generic;

public class InputData {
	private static int accNumber = 10000;

//	taking input for different options provided to user i.e. add an account , deposit or withdraw amount, 
	//display remaining balance and transferring amount from one account to another 
	public static void input(int option) throws IOException{
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

		if(option == 1) {
			// creating account 
			Account account = new Account();
			System.out.println("Enter the Account Holder Name : ");
			// taking input of relevant data   
			String name = br.readLine();
			accNumber += accNumber + 1;
			//setting account holder name which user has provided and account number which we have generated by our algorithm 
			account.setAccholdername(name);
			account.setAccnumber(accNumber);
			Generic.addAccount(account);
			System.out.println("Account has been created!!!");
			System.out.println("Your account number is : " + accNumber + " (Kindly note it down for further use)");
			Mainclass.welcome();

		} else if(option == 2 || option == 3) {
			// deposit and withdrawal
			System.out.println("Enter the Account Holder Account number : ");
			// taking input of relevant data 
			long accNmbr = Long.parseLong(br.readLine());
			
			if(option == 2) {
				System.out.println("Enter the amount to be deposited: ");
				// taking input of relevant data 
				double deposite = Double.parseDouble(br.readLine());
				Transaction.deposit(accNmbr, deposite);
			} else {
				System.out.println("Enter the amount to be withdrawal: ");
				// taking input of relevant data 
				double withdraw = Double.parseDouble(br.readLine());
				Transaction.withdraw(accNmbr, withdraw);
			}
		} else if(option == 4){
			// display balance
			System.out.println("Enter the Account Holder Name : ");
			// taking input of relevant data 
			String name = br.readLine();
			System.out.println("Enter the Account Holder Account number : ");
			// taking input of relevant data 
			long accNmbr = Long.parseLong(br.readLine());
			
			Transaction.viewbalance(name, accNmbr);
		} else if(option == 5){
			// long, long, double
			System.out.println("Enter the account number from whom amount is to be transfered : ");
			// taking input of relevant data 
			long accNmbr1 = Long.parseLong(br.readLine());
			System.out.println("Enter the account number to whom amount is to be transfered : ");
			// taking input of relevant data 
			long accNmbr2 = Long.parseLong(br.readLine());
			System.out.println("Enter the amount to be transfered : ");
			// taking input of relevant data 
			double amount = Double.parseDouble(br.readLine());
			
			Transaction.transfer(accNmbr1, accNmbr2, amount);
		}
	}
}
